/* See LICENSE file for copyright and license details. */
#ifndef OLM_SESSION_H_
#define OLM_SESSION_H_

#include "libce/ratchet.h"

// Note: exports in this file are only for unit tests.  Nobody else should be
// using this externally
#include "libce/olm_export.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct OlmAccount OlmAccount;

typedef enum MessageType {
    MESSAGE_TYPE_PRE_KEY = 0,
    MESSAGE_TYPE_MESSAGE = 1
} MessageType;

typedef struct OlmSession {
    OlmErrorCode last_error;
    _OlmRatchet ratchet;
    _olm_curve25519_public_key alice_identity_key;
    _olm_curve25519_public_key alice_base_key;
    _olm_curve25519_public_key bob_one_time_key;
    bool received_message;
} OlmSession;

/** Initialise an Olm session object. */
void _olm_session_init(
    OlmSession * session
);

/** The number of random bytes that are needed to create a new outbound
 * session. This will be 64 bytes since two ephemeral keys are needed. */
size_t _olm_session_new_outbound_session_random_length(void);

/** Start a new outbound session. Returns SIZE_MAX on failure. On
 * failure last_error will be set with an error code. The last_error will be
 * NOT_ENOUGH_RANDOM if the number of random bytes was too small. */
size_t _olm_session_new_outbound_session(
    OlmSession * session,
    OlmAccount const * local_account,
    _olm_curve25519_public_key const * identity_key,
    _olm_curve25519_public_key const * one_time_key,
    uint8_t const * random, size_t random_length
);

/** Start a new inbound session from a pre-key message.
 * Returns SIZE_MAX on failure. On failure last_error will be set
 * with an error code. The last_error will be BAD_MESSAGE_FORMAT if
 * the message headers could not be decoded. */
size_t _olm_session_new_inbound_session(
    OlmSession * session,
    OlmAccount * local_account,
    _olm_curve25519_public_key const * their_identity_key,
    uint8_t const * pre_key_message, size_t message_length
);

/** The number of bytes written by session_id() */
size_t _olm_session_session_id_length(void);

/** An identifier for this session. Generated by hashing the public keys
 * used to create the session. Returns the length of the session id on
 * success or SIZE_MAX on failure. On failure last_error will be set
 * with an error code. The last_error will be OUTPUT_BUFFER_TOO_SMALL if
 * the id buffer was too small. */
size_t _olm_session_session_id(
    OlmSession * session,
    uint8_t * id, size_t id_length
);

/** True if this session can be used to decode an inbound pre-key message.
 * This can be used to test whether a pre-key message should be decoded
 * with an existing session or if a new session will need to be created.
 * Returns true if the session is the same. Returns false if either the
 * session does not match or the pre-key message could not be decoded.
 */
bool _olm_session_matches_inbound_session(
    OlmSession * session,
    _olm_curve25519_public_key const * their_identity_key,
    uint8_t const * pre_key_message, size_t message_length
);

/** Whether the next message will be a pre-key message or a normal message.
 * An outbound session will send pre-key messages until it receives a
 * message with a ratchet key. */
MessageType _olm_session_encrypt_message_type(
    OlmSession const * session
);

size_t _olm_session_encrypt_message_length(
    OlmSession * session,
    size_t plaintext_length
);

/** The number of bytes of random data the encrypt method will need to
 * encrypt a message. This will be 32 bytes if the session needs to
 * generate a new ephemeral key, or will be 0 bytes otherwise. */
size_t _olm_session_encrypt_random_length(
    OlmSession * session
);

/** Encrypt some plain-text. Returns the length of the encrypted message
  * or SIZE_MAX on failure. On failure last_error will be set with
  * an error code. The last_error will be NOT_ENOUGH_RANDOM if the number
  * of random bytes is too small. The last_error will be
  * OUTPUT_BUFFER_TOO_SMALL if the output buffer is too small. */
size_t _olm_session_encrypt(
    OlmSession * session,
    uint8_t const * plaintext, size_t plaintext_length,
    uint8_t const * random, size_t random_length,
    uint8_t * message, size_t message_length
);

/** An upper bound on the number of bytes of plain-text the decrypt method
 * will write for a given input message length. */
size_t _olm_session_decrypt_max_plaintext_length(
    OlmSession * session,
    MessageType message_type,
    uint8_t const * message, size_t message_length
);

/** Decrypt a message. Returns the length of the decrypted plain-text or
 * SIZE_MAX on failure. On failure last_error will be set with an
 * error code. The last_error will be OUTPUT_BUFFER_TOO_SMALL if the
 * plain-text buffer is too small. The last_error will be
 * BAD_MESSAGE_VERSION if the message was encrypted with an unsupported
 * version of the protocol. The last_error will be BAD_MESSAGE_FORMAT if
 * the message headers could not be decoded. The last_error will be
 * BAD_MESSAGE_MAC if the message could not be verified */
size_t _olm_session_decrypt(
    OlmSession * session,
    MessageType message_type,
    uint8_t const * message, size_t message_length,
    uint8_t * plaintext, size_t max_plaintext_length
);

/**
 * Write a string describing this session and its state (not including the
 * private key) into the buffer provided.
 *
 * Takes a buffer to write to and the length of that buffer
 */
void _olm_session_describe(
    OlmSession * session,
    char *buf, size_t buflen
);

size_t _olm_pickle_session_length(
    OlmSession const * value
);

uint8_t * _olm_pickle_session(
    uint8_t * pos,
    OlmSession const * value
);

CE_EXPORT uint8_t const * _olm_unpickle_session(
    uint8_t const * pos, uint8_t const * end,
    OlmSession * value
);

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* OLM_SESSION_H_ */
